version: "3.9"
networks:
  roboshop:
    driver: bridge
services:
  web:
    image: ramakrishnareddithi/web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
  mongodb:
    image: ramakrishnareddithi/mongodb:v1
    container_name: mongodb
  catalogue:
    image: ramakrishnareddithi/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis
    container_name: redis
  user:
    image: ramakrishnareddithi/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    image: ramakrishnareddithi/cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue
  mysql:
    image: ramakrishnareddithi/mysql:v1
    container_name: mysql

  shipping:
    image: ramakrishnareddithi/shipping:v1
    container_name: shipping
    depends_on:
      - mysql

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq


  payment:
    image: ramakrishnareddithi/payment:v1
    container_name: payment
    depends_on:
      - rabbitmq

  ratings:
    image: ramakrishnareddithi/ratings:v1
    container_name: ratings
    depends_on:
      - mysql


